//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.DesenvolvimentoWeb.CadastroEventos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEVENTOSEntities : DbContext
    {
        public DBEVENTOSEntities()
            : base("name=DBEVENTOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBConvidados> TBConvidados { get; set; }
        public virtual DbSet<TBEventos> TBEventos { get; set; }
    }
}
