//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.DesenvolvimentoWeb.CadastroEventos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBConvidados
    {
        public int IDConvidado { get; set; }
        public Nullable<int> IDEvento { get; set; }
        public string Convidado { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
    
        public virtual TBEventos TBEventos { get; set; }
    }
}
