//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.DesenvolvimentoWeb.CadastroEventos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class TBEventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBEventos()
        {
            this.TBConvidados = new HashSet<TBConvidados>();
        }

        public int IDEvento { get; set; }

        [DisplayName("Data do Evento")]
        [Required(ErrorMessage = "A data é obrigatória")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Data { get; set; }

        [DisplayName("Descrição")]
        [Required(ErrorMessage = "A descrição é obrigatória")]
        public string Descricao { get; set; }

        [DisplayName("Endereço do Evento")]
        [Required(ErrorMessage = "O endereço é obrigatório")]
        [StringLength(100, MinimumLength = 1)]
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Responsavel { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBConvidados> TBConvidados { get; set; }
    }
}
